# Generated by Django 5.0.3 on 2024-03-13 10:08

import modules.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='title',
            field=models.CharField(max_length=300, validators=[modules.validators.validate_title], verbose_name='название'),
        ),
    ]
